name: Build and Release Electron

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: win
            artifact: windows
            files: |
              dist/*.exe
              dist/*.yml

          - os: macos-latest
            platform: mac
            artifact: macos
            files: |
              dist/*.dmg
              dist/*.yml

          - os: ubuntu-latest
            platform: linux
            artifact: linux
            files: |
              dist/*.AppImage
              dist/*.yml

    runs-on: ${{ matrix.os }}

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Electron app
        run: npm run dist -- --${{ matrix.platform }} --publish always

      - name: Upload artifact backup
        uses: actions/upload-artifact@v4
        with:
          name: stellalauncher-${{ matrix.artifact }}
          path: ${{ matrix.files }}
          if-no-files-found: error